services:
  db:
    image: postgres:16
    container_name: myapp-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: aton
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    container_name: csharp_app
    restart: unless-stopped
    build:
      context: .
      dockerfile: aton.api/Dockerfile
    depends_on:
      - db
    ports:
      - "5000:8080"
      - "5001:8081"
    environment:
      - ConnectionStrings__Default=Host=db;Database=aton;Username=admin;Password=password
